import type { Config } from "./config.js";
import { defaultMimeAllowlist, parseCwdAllowlist } from "./media.js";

export function createTestConfig(
  stateDir: string,
  overrides: Partial<Config> = {},
): Config {
  return {
    TELEGRAM_BOT_TOKEN: "123456789:test-token-not-real",
    AGENT_PROVIDER: "grok",
    AGENT_CWD: stateDir,
    AGENT_BIN: "",
    AGENT_MODEL: "grok-4.5",
    AGENT_DISPLAY_NAME: "",
    STATE_DIR: stateDir,
    AGENT_CWD_ALLOWLIST: "",
    AGENT_ALWAYS_APPROVE: false,
    PAIRING_EXPIRY_MS: 300_000,
    PAIRING_PENDING_MAX: 100,
    PERMISSION_TIMEOUT_MS: 300_000,
    LOCK_STALE_AFTER_MS: 135_000,
    PROMPT_STALE_AFTER_MS: 900_000,
    MAX_TYPING_SESSION_MS: 1_800_000,
    STREAM_EDIT_INTERVAL_MS: 1_500,
    STREAM_MIN_DELTA_CHARS: 24,
    STREAM_DRAFT_MAX: 3_800,
    PROGRESS_NOTICE_AFTER_MS: 90_000,
    PROGRESS_NOTICE_INTERVAL_MS: 120_000,
    PROGRESS_NOTICE_ITERATION_MS: 60_000,
    PROGRESS_NOTICE_MAX_ITERATIONS: 90,
    SEND_PACE_MS: 50,
    TELEGRAM_OUTBOUND_QUEUE_MAX: 100,
    TELEGRAM_RETRY_MAX: 5,
    ASSISTANT_TEXT_MAX_CHARS: 200_000,
    TYPING_INTERVAL_MS: 4_000,
    TYPING_DEBOUNCE_MS: 60_000,
    HEALTH_WRITE_MIN_INTERVAL_MS: 5_000,
    API_TIMEOUT_MS: 30_000,
    PERMISSION_SUMMARY_MAX: 1_800,
    MEDIA_MAX_BYTES: 20 * 1024 * 1024,
    MEDIA_MIME_ALLOWLIST: "",
    PROMPT_QUEUE_MAX: 3,
    CANCEL_WAIT_MS: 15_000,
    RETRY_LAST_TTL_MS: 30 * 60 * 1000,
    WATCHDOG_INTERVAL_MS: 30_000,
    BUBBLE_DEBOUNCE_MS: 300,
    THOUGHT_EDIT_INTERVAL_MS: 2_500,
    VERBOSE_DEFAULT: false,
    stateDir,
    agentProvider: "grok",
    agentCwdAbs: stateDir,
    agentBin: "grok",
    agentModel: "grok-4.5",
    agentAlwaysApprove: false,
    agentDisplayName: "Grok Build",
    mimeAllowlist: defaultMimeAllowlist(),
    cwdAllowlist: parseCwdAllowlist("", stateDir),
    ...overrides,
  };
}
